import Header from '@components/Header/Header';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

import '@styles/globals.css';
import '@styles/reset.css';
import Footer from '@components/Footer/Footer';

const roboto = Roboto({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="wrapper">
          <Header />
          <main className=" flex-grow">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
